# Generated by Django 4.2 on 2023-05-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileinfo",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="media/profile_pics"),
        ),
    ]
