# Generated by Django 4.2 on 2023-04-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms_practice", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="users",
            new_name="NewUsers",
        ),
    ]
