# Generated by Django 4.2 on 2023-05-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_practice", "0002_rename_users_newusers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newusers",
            name="email_Id",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
